name: Get & cache dependencies
description: Get dependencies (via npm) and cache them for future runs
inputs:
  service:
    description: "The service to get dependencies for"
    required: true
  caching:
    description: "The caching strategy to use"
    required: false
    default: "true"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.cache-outputs.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.service }}/node_modules
        key: deps-node-modules-${{ hashFiles(format('{0}/package-lock.json', inputs.service)) }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: cd ${{ inputs.service }} && npm install --omit=dev
      shell: bash
    - name: Set cache-hit output
      id: cache-outputs
      run: echo "cache-hit=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash
