name: Get & cache dependencies
description: Get dependencies (via npm) and cache them for future runs
inputs:
  serivce:
    description: "The service to get dependencies for"
    required: true
  caching:
    description: "The caching strategy to use"
    required: false
    default: "true"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.cache-outputs.outputs.cache-hit }}
  service-directory:
    description: "The service directory"
    value: ${{ steps.service-directory.outputs.service-directory }}
runs:
  using: "composite"
  steps:
    - name: Service directory
      id: service-directory
      run: echo "service-directory=${{ github.workspace }}/${{ inputs.service }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Go to service directory
      run: cd ${{ steps.service-directory.outputs.service-directory }}
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm install --omit=dev
      shell: bash
    - name: Set cache-hit output
      id: cache-outputs
      run: echo "cache-hit=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash
