name: Deploy Auth Service
on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: build auth image
        run: |
          docker build -t baoha7204/tickix-auth auth
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: baoha7204
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        run: |
          docker push baoha7204/tickix-auth
      