name: Deploy Manifests
on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
env:
  AUTH_IMAGE: ${{ vars.DOCKERHUB_AUTH_IMAGE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Switch to the correct context
        run: |
          doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
        env:
          CLUSTER_NAME: ${{ vars.DIGITALOCEAN_KUBERNETES_CLUSTER }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/k8s &&
          kubectl apply -f infra/k8s-prod
