name: Deploy Payments Service
on:
  push:
    branches:
      - master
    paths:
      - "payments/**"
env:
  PAYMENTS_IMAGE: baoha7204/tickix-payments
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: build payments image
        run: |
          docker build -t $PAYMENTS_IMAGE payments
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        run: |
          docker push $PAYMENTS_IMAGE
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Switch to the correct context
        run: |
          doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
        env:
          CLUSTER_NAME: ${{ vars.DIGITALOCEAN_KUBERNETES_CLUSTER }}
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment payments-depl
